"""
Build a static export of the Reflection-Level Interactive tool for GitHub Pages.

Renders templates/reflection.html with plain relative asset paths (no Flask
url_for/request context needed) into docs/index.html, and copies the CSS/JS
into docs/static/. Endpoint images already live in docs/reflection-images/
(generated by scripts/build_reflection_endpoints.py) and are picked up
automatically -- regenerate them and re-run this script.

Run:  python scripts/build_static.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

BASE_DIR = Path(__file__).resolve().parent.parent
DOCS_DIR = BASE_DIR / "docs"

sys.path.insert(0, str(BASE_DIR))
from reflection_data import group_reflection_files  # noqa: E402


def build_items():
    items = []
    for base, files in sorted(group_reflection_files().items()):
        items.append(
            {
                "name": base,
                "original_url": f"reflection-images/{files['original']}",
                "base_url": f"reflection-images/{files['base']}",
                "bodyclean_url": f"reflection-images/{files['bodyclean']}",
            }
        )
    return items


def main():
    (DOCS_DIR / "static" / "css").mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "static" / "js").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(
        BASE_DIR / "static" / "css" / "style.css",
        DOCS_DIR / "static" / "css" / "style.css",
    )
    shutil.copyfile(
        BASE_DIR / "static" / "js" / "reflection.js",
        DOCS_DIR / "static" / "js" / "reflection.js",
    )

    env = Environment(loader=FileSystemLoader(str(BASE_DIR / "templates")))
    template = env.get_template("reflection.html")
    items = build_items()
    html = template.render(
        items=items,
        css_url="static/css/style.css",
        js_url="static/js/reflection.js",
    )
    (DOCS_DIR / "index.html").write_text(html, encoding="utf-8")
    print(f"wrote {DOCS_DIR / 'index.html'}  ({len(items)} cars)")


if __name__ == "__main__":
    main()
